/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.superurop.activitydetection.datahub.java;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked"})
public class datahubConstants {

  public static final double VERSION = 1;

}
